# Generated by Django 4.1.5 on 2024-01-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('l', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('CM', 'Cosmetic'), ('EL', 'Electronics')], max_length=2),
        ),
    ]
